services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpass
    volumes:
      - ./docker/keycloak/keycloak-realm.json:/opt/keycloak/data/import/realm.json
    networks:
      - backend

  discovery-server:
    build:
      context: .
      dockerfile: ./discovery-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - backend

  api-gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - keycloak
    networks:
      - backend

  crm-service:
    build:
      context: .
      dockerfile: ./services/crm/Dockerfile
    depends_on:
      - mysql
      - kafka
      - discovery-server
    networks:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    networks:
      - backend
    depends_on:
      - api-gateway


#  auth-service:
#    build:
#      context: .
#      dockerfile: ./services/auth/Dockerfile
#    depends_on:
#      - mysql
#      - kafka
#      - discovery-server
#    networks:
#      - backend

#  billing-service:
#    build:
#      context: .
#      dockerfile: ./services/billing/Dockerfile
#    depends_on:
#      - mysql
#      - kafka
#      - discovery-server
#    networks:
#      - backend

#  time-tracking-service:
#    build:
#      context: .
#      dockerfile: ./services/time-tracking/Dockerfile
#    depends_on:
#      - mysql
#      - kafka
#      - discovery-server
#    networks:
#      - backend

volumes:
  mysql_data:

networks:
  backend:
